In [399]:
#Import numpy and Matplotlib modules
import numpy as np
import matplotlib.pyplot as plt
#ignore warning message
import warnings
warnings.filterwarnings('ignore')
import pandas as pd
import seaborn as sns

# Part 1: Probability

In [400]:
df = pd.read_csv('credit_card.csv')

In [401]:
df.head()

,gender,age,job,marital,education,default,housing,loan,contact,CreditCard
0,female,56,housemaid,married,basic.4y,no,no,no,telephone,no
1,male,57,services,married,high.school,yes,no,no,telephone,no
2,female,37,services,married,high.school,no,yes,no,telephone,no
3,female,40,admin.,married,basic.6y,no,no,no,telephone,no
4,female,56,services,married,high.school,no,no,yes,telephone,no

In [402]:
df.shape

(41188, 10)

In [403]:
df.describe(include='all')

,gender,age,job,marital,education,default,housing,loan,contact,CreditCard
count,41188,41188.00000,41188,41188,41188,41188,41188,41188,41188,41188
unique,2,NaN,12,4,8,2,2,2,2,2
top,female,NaN,admin.,married,university.degree,no,yes,no,cellular,no
freq,20798,NaN,10422,24928,12168,32588,22566,33950,26144,36548
mean,NaN,40.02406,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
std,NaN,10.42125,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
min,NaN,17.00000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25%,NaN,32.00000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50%,NaN,38.00000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75%,NaN,47.00000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
max,NaN,98.00000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [404]:
df.columns

Index(['gender', 'age', 'job', 'marital', 'education', 'default', 'housing',
       'loan', 'contact', 'CreditCard'],
      dtype='object')

In [405]:
total = df.shape[0]

## Q1: What is the Probability that the Customer has a Credit Card ?

In [406]:
p_card = len(df[df['CreditCard'] == 'yes']) / total
p_card

0.11265417111780131

## Q2: What is the Probability that the Customer age is greater than 50 ?

In [407]:
p_age_50 = len(df_cc[df_cc['age'] > 50]) / total
p_age_50

0.17432261823832185

## Q3: What is the probability that the customer is illiterate?

In [408]:
p_illiterate = len(df_cc[df_cc['education'] == 'illiterate']) / total
p_illiterate

0.0004370204914052637

## Q4: What is the Probability that the Customer has a Telephone ?

In [409]:
p_phone = len(df[df['contact'] == 'telephone']) / total
p_phone

0.3652520151500437

## Q5: What is the Probability that the Customer is Single and has a Credit Card ?

In [410]:
p_single_card = len(df[(df['marital'] == 'single') & (df['CreditCard'] == 'yes')]) / total
p_single_card

0.03933184422647373

## Q6: What is the Probability that the Customer is Male and has at most 6 Year of Education ?

In [411]:
p_male_edu = len(df[(df['gender'] == 'male') & (df['education'].isin(['basic.4y', 'basic.6y']))]) / total
p_male_edu

0.0775711372244343

## Q7: What is the Probability that the Customer is Retired and is divorced ?

In [412]:
p_retired_divorced = len(df[(df['job'] == 'retired') & (df['marital'] == 'divorced')]) / total
p_retired_divorced

0.008449062833835098

## Q8: Given the Customer has the credit card, find the probability that he/she is married ?

In [413]:
has_card = df[df['CreditCard'] == 'yes']
p_married = len(has_card[has_card['marital'] == 'married']) / len(has_card)
p_married

0.5456896551724137

## Q9: If a customer has a management job, find the probability that he has a housing

In [414]:
job_filter = df[df['job'] == 'management'] 
p_housing = len(job_filter[job_filter['housing'] == 'yes']) / len(job_filter)
p_housing

0.5338577291381669

# Part 2: Bayes Theorem

In [415]:
df = pd.read_csv('kerala_floods.csv')

In [416]:
df.head()

,SUBDIVISION,YEAR,JAN,FEB,MAR,APR,MAY,JUN,JUL,AUG,SEP,OCT,NOV,DEC,ANNUAL RAINFALL,FLOODS
0,KERALA,1901,28.7,44.7,51.6,160.0,174.7,824.6,743.0,357.5,197.7,266.9,350.8,48.4,3248.6,YES
1,KERALA,1902,6.7,2.6,57.3,83.9,134.5,390.9,1205.0,315.8,491.6,358.4,158.3,121.5,3326.6,YES
2,KERALA,1903,3.2,18.6,3.1,83.6,249.7,558.6,1022.5,420.2,341.8,354.1,157.0,59.0,3271.2,YES
3,KERALA,1904,23.7,3.0,32.2,71.5,235.7,1098.2,725.5,351.8,222.7,328.1,33.9,3.3,3129.7,YES
4,KERALA,1905,1.2,22.3,9.4,105.9,263.3,850.2,520.5,293.6,217.2,383.5,74.4,0.2,2741.6,NO

In [417]:
df.shape

(118, 16)

In [418]:
df.isnull().sum()

SUBDIVISION         0
YEAR                0
JAN                 0
FEB                 0
MAR                 0
APR                 0
MAY                 0
JUN                 0
JUL                 0
AUG                 0
SEP                 0
OCT                 0
NOV                 0
DEC                 0
 ANNUAL RAINFALL    0
FLOODS              0
dtype: int64

## 1- We may start by preparing the required columns:

In [419]:
df['June_more_than_500'] = (df['JUN'] > 500).astype(int)
df['FLOODS_BINARY'] = df['FLOODS'].map({'YES': 1, 'NO': 0})

## 2- Select only the columns that will help to answer the main question.

In [420]:
df_analysis = df[['June_more_than_500', 'FLOODS_BINARY']]
df_analysis.head()

   June_more_than_500  FLOODS_BINARY
0                   1              1
1                   0              1
2                   1              1
3                   1              1
4                   1              0

## 3- Create a cross tabulation for 'FLOODS' and 'June_more_than_500'

In [431]:
ct = pd.crosstab(df['FLOODS_BINARY'], df['June_more_than_500'], margins=True)
ct

June_more_than_500   0   1  All
FLOODS_BINARY
0                   19  39   58
1                    6  54   60
All                 25  93  118

## 4- What is the probability of a rainfall more than 500mm in June?

In [422]:
total = df.shape[0]

In [423]:
p_june_high = len(df[df['June_more_than_500'] == 1]) / total
p_june_high

0.788135593220339

## 5- What is the probability of having a flood?

In [424]:
p_flood = len(df[df['FLOODS_BINARY'] == 1]) / total
p_flood

0.5084745762711864

## 6- What is the probability of having a flood and a rainfall more than 500mm in June?

In [425]:
p_flood_and_june = len(df[(df['FLOODS_BINARY'] == 1) & (df['June_more_than_500'] == 1)]) / total
p_flood_and_june

0.4576271186440678

## 7- What is the Probability of having a flood given it rained more than 500mm in June?

In [426]:
p_flood_given_june_high = p_flood_and_june / p_june_high
p_flood_given_june_high

0.5806451612903226

## 8- What is the probability of a rainfall less than 500mm in June?

In [427]:
p_june_low = 1 - p_june_high
p_june_low

0.211864406779661

## 9- What is probability of having a flood given that it rained less than 500mm?

In [428]:
p_flood_and_june_low = len(df[(df['FLOODS_BINARY'] == 1) & (df['June_more_than_500'] == 0)]) / total
p_flood_given_june_low = p_flood_and_june_low / p_june_low

p_flood_given_june_high

0.5806451612903226

## 10- Answer this question by using Bayes Theorem and the law of the Total Probaility

In [429]:
numerator = p_flood_given_june_high * p_june_high
p_b = (p_flood_given_june_high * p_june_high) + (p_flood_given_june_low * p_june_low)

res_10 = numerator / p_b
round(res_10, 2)

0.9

## 11- Answer this question by using Bayes Theorem only.

In [430]:
res_11 = (p_flood_given_june_high * p_june_high) / p_flood

round(res_11, 2)

0.9